name: publish

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checks out a copy of the repository on the runners machine
      - name: Checkout repository
        uses: actions/checkout@master
    # Install Java
      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version 1.8
    # Setup leiningen
      - name: Setup Leiningen
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.9.1
    # Build the site
      - name: Build blog
        run: lein run
    # Commit the build
      - name:  Commit build
        uses: EndBug/add-and-commit@v7
        with: 
          add: 'public -f'
          author_name: UnwarySage
          author_email: shawx538@morris.umn.edu
          branch: gh-pages
          message: "auto-publish"

